### PR TITLE
Mapl expose label styles as h5

### PR DESCRIPTION
**Pull request by marcopluess**

### CODE REVIEW

**Comment by marcopluess** [comment]
@lgavillet: ready for review! wohoo

**Comment by lgavillet** [comment]
All good, @sled ok for you?

**Comment by marcopluess** [comment]
@sled: to test it in your lendit branch, you will have to update _variables.scss of lendit:

screen shot 2016-08-30 at 12 12 36

**Comment by sled** [comment]
Works for me :)

**Comment by lgavillet** [comment]
Thanks for the job

**Pull request merged**
