### PR TITLE
removed exceptional font defititions to buttons and tabs

### PR DESCRIPTION
**Pull request by marcopluess**

### CODE REVIEW

**Comment by marcopluess** [comment]
please merge

**Comment by lwe** [comment]
but... without there is additional letter-spacing and the wrong font-weight...

**Comment by lwe** [comment]
(according to @florianwestermann)

**Comment by marcopluess** [comment]
you said preferably no exceptions to the materializer standard.

**Comment by marcopluess** [comment]
and tabs in bold use waaay too much space

**Comment by lwe** [comment]
Discuss with @florianwestermann

**Comment by lwe** [comment]
(Personally, I think it's a reasonable change and within what mtl should / can do.)

**Comment by marcopluess** [comment]
denn loemmers

**Pull request closed without merging**
