### PR TITLE
Collapsibles: add support for collapsible and accordion toggles

### PR DESCRIPTION
**Pull request by lwe**
As discussed separately this implements the markup to follow what collapsible and adds an additional external trigger for the toggle.

- Add wrapper for turbolinks: data-mtl-collapsible
- Support external toggle via: data-mtl-collapsible-toggle="#ref"

Please review and check `REFERENCE.md` for documentation and usage, danke.

See also #22

### CODE REVIEW

**Comment by sled** [comment]
cool! one suggestion, would it be possible to add a CSS class also to the trigger like `.first` and `.second` so we can easily show a triangle chevron (\/, /\) ?

**Comment by lwe** [comment]
you can already to this via the `.active` class being added, as follows:

```erb
<div data-mtl-collapsible-trigger="#other" class="active"> <!-- the .active is toggled! -->
   Some text
   
   <div class="right indicator">
     <%= mtl_icon :arrow_drop_down %>
     <%= mtl_icon :arrow_drop_up %> 
   </div>
</div>
```

and the relevant css is something like:

```
.indicator i { display: none; }
.active .indicator i:nth-child(2),
:not(.active) .indicator i:nth-child(1) {
  display: inline-block;
}
```

**Comment by lwe** [comment]
@sled would that work too?

**Comment by lwe** [comment]
^^ merged, thanks for the feedback

**Pull request merged**
