### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by lwe**
Plan is to use yard / yardoc to provide the documentation, all Ruby helpers have already been commented. Additional specific docs need to be created for CSS and JS helpers.

### CODE REVIEW

**Comment by lwe** [comment]
@marcopluess, @sled and @lgavillet want to merge this tomorrow, can you please review - the documentation can be generated by running the following:

```
./bin/yardoc
open doc/index.html
```

**Comment by lwe** [comment]
PS: Yep, the pictures referenced are not optimal, not yet sure what we should use TBH... maybe via gh-pages?

**Comment by lgavillet** [comment]
A bit confused by the layout part, but otherwise yep 👍

**Comment by lwe** [comment]
Open for suggestions and improvements, the Layout part should explain the markup for the different layouts we provide.

**Comment by lgavillet** [comment]
Ok i think i'm just confused by the fact it's html layouts and not 'already included in the gem' layouts. But all good.

**Comment by lwe** [comment]
Okay, because we don't know what kind of thing you want to but between `<head></head>` et all, so I think it's hard to provide a generic layout... we could however provide a generator, open to that suggestion, like:

```
./bin/rails g mtl:layout [--default | --simple] <layout name>
```

but this is post v1 I'd say, as we don't generate layouts that often, but I agree an opinionated layout would be very useful too!

**Comment by lgavillet** [comment]
Ok would be nice in the future

**Comment by marcopluess** [comment]
added a new section to the readme, otherwise 👍 top.

once we have this merged, I can start a more comprehensive documentation on the different layouts

**Pull request merged**
